@startuml

actor Pengguna as "Pengguna"
actor Penjual as "Penjual"
actor Admin as "Admin"

Pengguna --> (Registrasi/Login)
Pengguna --> (Jelajahi Produk)
Pengguna --> (Tambah ke Keranjang)
Pengguna --> (Checkout dan Pembayaran)
Pengguna --> (Menerima Pesanan)
Pengguna --> (Selesai)

Penjual --> (Registrasi/Login)
Penjual --> (Kelola Produk)
Penjual --> (Menerima Pesanan)
Penjual --> (Mengatur Pengiriman)
Penjual --> (Menunggu Konfirmasi Konsumen)
Penjual --> (Analisis Penjualan)
Penjual --> (Selesai)

Admin --> (Login ke Sistem Admin)
Admin --> (Kelola Pengguna)
Admin --> (Kelola Produk)
Admin --> (Kelola Transaksi)
Admin --> (Menangani Keluhan)
Admin --> (Melihat Laporan & Analisis)
Admin --> (Selesai)

@enduml
