@startuml
start

:Buka Aplikasi EcoMarket;
:Login sebagai Admin;

:Kelola Pengguna (Verifikasi, Blokir, Hapus Akun);
:Kelola Produk (Tinjau, Hapus, Edit Produk);
:Kelola Transaksi (Pantau Status Pembayaran dan Pengiriman);
:Tangani Keluhan (Selesaikan Masalah antara Konsumen dan Produsen);
:Lihat Laporan & Analisis (Statistik Penjualan, Pengguna Aktif, dll.);

:Selesai;

stop
@enduml