@startuml
start
:Login ke Sistem Admin;
:Kelola Pengguna;
:Verifikasi Akun & Blokir Pengguna;
:Kelola Produk;
:Tinjau & Hapus Produk Tidak Sesuai;
:Kelola Transaksi;
:Memeriksa Pembayaran & Status Pesanan;
:Menangani Keluhan;
:Melihat Laporan & Analisis;
:Selesai;
stop
@enduml
