@startuml
start

:Buka Aplikasi EcoMarket;

if (Sudah punya akun?) then (Ya)
  :Login;
else (Tidak)
  :Registrasi;
  :Verifikasi Email;
endif

:Jelajahi Produk (Cari berdasarkan kategori/filter);
:Tambahkan Produk ke Keranjang;
:Checkout dan Pilih Metode Pembayaran;

if (Pembayaran Berhasil?) then (Ya)
  :Terima Pesanan;
  :Beri Ulasan/Rating;
else (Tidak)
  :Coba Lagi atau Batalkan Pesanan;
endif

:Selesai;

stop
@enduml