@startuml
start

:Buka Aplikasi EcoMarket;

if (Sudah punya akun?) then (Ya)
  :Login;
else (Tidak)
  :Registrasi;
  :Verifikasi Akun;
endif

:Kelola Produk (Tambah/Edit/Hapus Produk);

if (Ada Pesanan Baru?) then (Ya)
  :Terima Notifikasi Pesanan;
  :Proses Pesanan dan Atur Pengiriman;
  :Konfirmasi Pengiriman;
  :Terima Ulasan/Rating dari Konsumen;
else (Tidak)
  :Tidak Ada Pesanan;
endif

:Analisis Penjualan (Lihat Laporan Performa Produk);
:Selesai;

stop
@enduml